RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/examples/*'
    - 'spec/integration/*'
    - 'spec/system/*'
    - 'spec/e2e/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/Output:
  Exclude:
    - 'spec/support/**/*'
    - 'spec/config/**/*'
    - 'spec/fixtures/**/*'

RSpec/SubjectStub:
  Exclude:
    - 'spec/appraisal/gem_manager/ore_adapter_spec.rb'
