inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

# This tells RuboCop to add the exclusions in this file
# to the default exclusions (and those from other inherited files),
# rather than overwriting them.
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/*
    - certs/**/*
    - checksums/**/*
    - docs/**/*
    - fixtures/**/*
    - gemfiles/*.gemfile
    - pkg/**/*
    - results/**/*
    - spec/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

# TODO: We would need to implement Mutexes in order to make violations thread safe.
#       But even then they would still trigger the violation.
#       See: https://coderscat.com/ruby-change-current-working-directory/
ThreadSafety/DirChdir:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
