#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
require_relative "../lib/appraisal/version"
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Appraisal::Version::VERSION
  exit(0)
end

require "rubygems"
require "bundler/setup"
require "appraisal2"
require "appraisal/cli"

puts "== #{script_basename} v#{Appraisal::Version::VERSION} =="

begin
  Appraisal::CLI.start
rescue Appraisal::AppraisalsNotFound => e
  puts e.message
  exit(127)
end
