# frozen_string_literal: true

RSpec.describe "CLI", "appraisal generate" do
  it "generates the gemfiles" do
    build_gemfile <<-GEMFILE.strip_heredoc.rstrip
      source "https://gem.coop"

      gem "appraisal2", :path => "#{PROJECT_ROOT}"
    GEMFILE

    build_appraisal_file <<-APPRAISAL.strip_heredoc.rstrip
      appraise '1.0.0' do
        gem 'dummy', '1.0.0'
      end

      appraise '1.1.0' do
        gem 'dummy', '1.1.0'
      end
    APPRAISAL

    run "appraisal generate"

    expect(file("gemfiles/1.0.0.gemfile")).to be_exists
    expect(file("gemfiles/1.1.0.gemfile")).to be_exists
    expect(content_of("gemfiles/1.0.0.gemfile")).to eq <<-GEMFILE.strip_heredoc.rstrip
      # This file was generated by Appraisal2

      source "https://gem.coop"

      gem "appraisal2", :path => "#{PROJECT_ROOT}"
      gem "dummy", "1.0.0"
    GEMFILE
  end
end
