# frozen_string_literal: true

# Std Lib
require "fileutils"
require "pathname"

# This gem
require "appraisal/gemfile"
require "appraisal/command"
require "appraisal/customize"
require "appraisal/utils"
require "appraisal/gem_manager"

module Appraisal
  # Represents one appraisal and its dependencies
  class Appraisal
    attr_reader :name, :gemfile

    def initialize(name, source_gemfile)
      @name = name
      @gemfile = source_gemfile.dup
    end

    def eval_gemfile(*args)
      gemfile.eval_gemfile(*args)
    end

    def gem(*args)
      gemfile.gem(*args)
    end

    def remove_gem(*args)
      gemfile.remove_gem(*args)
    end

    def source(*args, &block)
      gemfile.source(*args, &block)
    end

    def ruby(*args)
      gemfile.ruby(*args)
    end

    def git(*args, &block)
      gemfile.git(*args, &block)
    end

    def path(*args, &block)
      gemfile.path(*args, &block)
    end

    def group(*args, &block)
      gemfile.group(*args, &block)
    end

    def install_if(*args, &block)
      gemfile.install_if(*args, &block)
    end

    def platforms(*args, &block)
      gemfile.platforms(*args, &block)
    end

    def gemspec(options = {})
      gemfile.gemspec(options)
    end

    def git_source(*args, &block)
      gemfile.git_source(*args, &block)
    end

    def write_gemfile
      File.open(gemfile_path, "w") do |file|
        signature =
          Customize.heading(self) || "This file was generated by Appraisal2"
        file.puts([comment_lines(signature), quoted_gemfile].join("\n\n"))
      end
    end

    def install(options = {})
      gem_manager = options.delete(:gem_manager) || options.delete("gem_manager") ||
        options.delete(:"gem-manager") || options.delete("gem-manager")
      manager = GemManager::Factory.create(gemfile_path, project_root, :manager => gem_manager)
      manager.install(options)
    end

    def update(gems = [], options = {})
      gem_manager = options.delete(:gem_manager) || options.delete("gem_manager") ||
        options.delete(:"gem-manager") || options.delete("gem-manager")
      manager = GemManager::Factory.create(gemfile_path, project_root, :manager => gem_manager)
      manager.update(gems)
    end

    def gemfile_path
      gemfile_root.mkdir unless gemfile_root.exist?

      gemfile_root.join(gemfile_name).to_s
    end

    def relative_gemfile_path
      File.join("gemfiles", gemfile_name)
    end

    def relativize
      current_directory = Pathname.new(Dir.pwd)
      relative_path = current_directory.relative_path_from(gemfile_root).cleanpath
      lockfile_content = File.read(lockfile_path)

      File.open(lockfile_path, "w") do |file|
        file.write(lockfile_content.gsub(
          / #{current_directory}/,
          " #{relative_path}",
        ))
      end
    end

    private

    def gemfile_root
      project_root + "gemfiles"
    end

    def project_root
      Pathname.new(Dir.pwd)
    end

    def gemfile_name
      "#{clean_name}.gemfile"
    end

    def lockfile_path
      "#{gemfile_path}.lock"
    end

    def clean_name
      name.gsub(/[^\w.]/, "_")
    end

    def comment_lines(heading)
      heading.lines.map do |line|
        if line.lstrip.empty?
          line
        else
          "# #{line}"
        end
      end.join
    end

    def quoted_gemfile
      return gemfile.to_s unless Customize.single_quotes

      gemfile.to_s.tr('"', "'")
    end
  end
end
